# -*- coding: utf-8 -*-
"""exp1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rcI5JKAqaZDU6Np45k9YVSDBVr1IZfGR
"""

a=5
b=4
c=6
x=4.5
y=a * x * x + b * x + c
print ("for the values of " + str(a) + "," + str(b) + "," + str(c) + " y is :" + str(y))