# -*- coding: utf-8 -*-
"""exp1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rcI5JKAqaZDU6Np45k9YVSDBVr1IZfGR
"""

a=float(input("Enter the a value:"))
b=float(input("Enter the b value:"))
c=float(input("Enter the c value:"))
x=float(input("Enter the x value:"))
y=a * x * x + b * x + c
print ("for the values of " ,a, "," ,b, ",",c, " y is :" ,y,)